name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5 libtinfo5 openjdk-17-jdk build-essential python3-pip

      - name: Install Buildozer
        run: |
          pip install --user --upgrade buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Prepare buildozer.spec
        run: |
          if [ -f buildozer.spec ]; then
              echo "android.accept_sdk_license = True" >> buildozer.spec
          else
              echo "android.accept_sdk_license = True" > buildozer.spec
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Eye-Commander-Build
          path: bin/*.apk